### ISSUE TITLE
JS code not able to transpile  this dependancy

### ISSUE THREAD

**Issue by mohammedalnuaimi** [Georgegriff/query-selector-shadow-dom#10]
This repo not working with Jest, it alway throws an error about transpilation, I follow instracution from Jest and Babel, but still throwing the following error

_**Jest encountered an unexpected token**

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    **Details**:

    /Users/xxxxx/node_modules/query-selector-shadow-dom/src/querySelectorDeep.js:20
    export function querySelectorAllDeep(selector, root = document) {
    ^^^^^^

    SyntaxError: Unexpected token export

      2 | /* eslint-disable eslint-comments/disable-enable-pair */
      3 | import 'core-js';
    > 4 | import { querySelectorAllDeep } from 'query-selector-shadow-dom';_

**and another error when hovering over the import statment**

Could not find a declaration file for module 'query-selector-shadow-dom'. '/Users/xxxx/node_modules/query-selector-shadow-dom/src/querySelectorDeep.js' implicitly has an 'any' type.
  Try `npm install @types/query-selector-shadow-dom` if it exists or add a new declaration (.d.ts) file containing `declare module 'query-selector-shadow-dom';`ts(7016)

**Comment by Georgegriff** [comment]
If you're using it inside jest then that suggests to me that you're running it inside of a node environment. This module is for browser environments. It works with puppeteer because you can inject the script into the browser. I've tested the script using karma and that works fine. I have transpiled the script myself down to es5, using rollup. Perhaps if you take a look at my repo you can see how were using the module with karma. But unless you're using something like puppeteer this won't work in jest in node

**Comment by mohammedalnuaimi** [comment]
thanks @Georgegriff for your quick response, not sure what do you mean browser environment? 
yes I'm using it with Node you have mentioned that it's for selenuim and pupputeer that's why I've pick it up. so far spent two days trying to get this to work

**Comment by Georgegriff** [comment]
Could you provide a code sample of how you're trying to include the module to use it with your tests?

When I've used it with selenium and puppeteer I have been injecting the code into the browser, in selenium using the execute javascript commands

There is a transpiled es5 version of the library which is simplest to use to inject into the browser environment.

If I get an idea of what you're trying to do might be able to assist further

**Comment by Georgegriff** [comment]
https://github.com/Georgegriff/query-selector-shadow-dom/blob/master/puppeteer-es5.js

Shows how to inject the script into the browser directly in puppeteer. Load script tag which puts the module on the window

**Comment by mohammedalnuaimi** [comment]
here is an example, I just started using pupputeer, 

/* eslint-disable jest/expect-expect */
/* eslint-disable eslint-comments/disable-enable-pair */
import 'core-js';
import { querySelectorAllDeep } from 'query-selector-shadow-dom';
import { join } from 'path';
import { launch } from 'puppeteer';

describe('Login to ACC portal', () => {
  it('Login to acc', async () => {
    const browser = await launch({ headless: false, slowMo: 50 });
    const page = await browser.newPage();
    await page.goto('https://mdn.github.io/web-components-examples/popup-info-box-web-component/?');
    // await page.addScriptTag({
    //   path: join(__dirname, 'node_modules/query-selector-shadow-dom/dist/querySelectorShadowDom.js'),
    // });

    // const downloads = await page.evaluate(() => {
    //   const anchors = Array.from(querySelectorShadowDom.querySelectorAllDeep('a'));
    //   return anchors.map(anchor => anchor.href);
    // });
    console.log(querySelectorAllDeep);

    await page.waitFor('#cvc');
    await page.type('#cvc', 'hey');
    // expect(1).toBe.length(1);
    //await page.screenshot({ path: 'example.png' });
    browser.close();
  });
});

**Comment by Georgegriff** [comment]
So below core-js don't import the library there. You don't need it at all. You see the import script line that is loading the library into the page. Which means that "querySelectorAllDeep" will be available inside all the page.evaluate functions.

page.evalaute runs in the context of the browser which is why the library is available after the `page.addScriptTag` call.

So to fix your issue remove the import at the top of the file.

I'd read up on puppeteer and try to understand the difference between code running inside of the browser context of puppeteer Vs the nodejs (jest) context.

**Comment by Georgegriff** [comment]
To use the library you will need to do so inside page.evaluate in puppeteer, it will not work outside of those callbacks. The reason for this is the library needs the browser DOM tree to function. Hopefully this clears things up a bit.

**Comment by mohammedalnuaimi** [comment]
Cheers @Georgegriff  I got your point, will try to use in the browser context, but would be great to also clarify this in the docs, as some people like me will think that they need to use import to use it :)

**Comment by Georgegriff** [comment]
To close this issue, when I get time I'll try to flesh out a better example :)

**Comment by mohammedalnuaimi** [comment]
@Georgegriff  I don't seem to locate the shadow element using the suggest solution, would really appreciate if you could demonstrate to me how you would find it based on the example I sent above?

**Comment by Georgegriff** [comment]
@mohammedalnuaimi I've added a couple examples to this folder:
https://github.com/Georgegriff/query-selector-shadow-dom/tree/master/examples/puppeteer

https://github.com/Georgegriff/query-selector-shadow-dom/blob/master/examples/puppeteer/typing-to-elements.js - shows typing to an <input> element that is inside of a shadow root

https://github.com/Georgegriff/query-selector-shadow-dom/blob/master/examples/puppeteer/clicking-elements.js - shows clicking a <button> that is inside of a shadow root

They show how you can use the evaluate functions to get an "ElementHandle" which lets you automate elements: https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#class-elementhandle


Hopefully this will help you to understand. There page the demo is written on shouldn't really matter i just created a page which has some elements inside of shadow-roots, like below
![image](https://user-images.githubusercontent.com/9056958/64928401-cb64ca00-d80f-11e9-87b5-14010346af5c.png)

**Comment by mohammedalnuaimi** [comment]
Thanks @Georgegriff , I actually was not doing waitforfunction, that fixed the issue, cheers

**Comment by Georgegriff** [comment]
@mohammedalnuaimi Thanks for raising the issue I have much better examples now thanks to you. If find you end up developing some code that would work nicely for some more examples in the repo, prs always welcome

**Comment by mohammedalnuaimi** [comment]
hey @Georgegriff  I know this issue is closed, but wanted to ask another question, I'm trying to get the innerHTML of the a shadow elements, but not able to do it. 
my question here, will the queried Shadow dom return the an element object same as any element that we can hook and get it's innerHTML or InnerText ?

like this?

   const item = await page.evaluateHandle(() => {
      return querySelectorShadowDom.querySelectorAllDeep('login-button');
    })

    const value = await page.evaluate(item => item.innerHTML, item);

**Comment by vipin705** [comment]
hi @Georgegriff ,

i am trying to use this selector but i am seeing the below error 

 Query set to use "shadow", but no query handler of that name was found


here is my code 


import * as puppeteer from 'puppeteer';
import { Given, Then, When } from 'cucumber';
import { join } from 'path';

let browser: puppeteer.Browser, page: puppeteer.Page;

Given('I load time off component', { timeout: 2 * 5000 }, async () => {
  browser = await puppeteer.launch({
    headless: false,
    defaultViewport: null,
    args: ['--start-maximized']
  });
  page = await browser.newPage();
  const response = await page.goto(`http://localhost:5000/#/time_dashboard`);
  await page.addScriptTag({
    path: join(
      'node_modules/query-selector-shadow-dom/dist/querySelectorShadowDom.js'
    )
  });
  page.waitForNavigation();
  await page.waitForSelector('shadow/.size-sm.contained.standard.secondary');
  const btn = await page.$('shadow/.size-sm.contained.standard.secondary');
  await btn.click();
  return response;
});

**Comment by Georgegriff** [comment]
Can you create a separate  issue rather than on an unrelated issue please
