### ISSUE TITLE
nested shadow-root (open) is not clickable

### ISSUE THREAD

**Issue by naveenmadd** [Georgegriff/query-selector-shadow-dom#12]
Steps to reproduce this issue
using latest puppeteer-core(2.0.0 version)
tried to use the SelectorDeep & SelectorAllDeep from query-selector-shadow-dom, i'm getting the btn.click() is **not visible or HTMLelement** while trying to click the Default button on the pop-up as shown in figure-1 & figure-2 is it's DOM view with nested shadow-root where **<iron-icon> icon="paper-dropdown-menu:arrow-drop-down"**

tried to use the  SelectorAllDeep from query-selector-shadow-dom, i'm getting the**btn is not clickable function**
@Georgegriff please help me, what i'm missing here

![image](https://user-images.githubusercontent.com/57717430/68776637-6dc9df80-05fe-11ea-8066-eb183832c61c.png)
![image](https://user-images.githubusercontent.com/57717430/68776695-86d29080-05fe-11ea-8928-78edce7819a6.png)

**Comment by Georgegriff** [comment]
Can you provide your puppet code?

**Comment by Georgegriff** [comment]
Can you provide your exact arguments passed to the library `icon="paper-dropdown-menu:arrow-drop-down` on its own is not a valid CSS selector `[icon="paper-dropdown-menu:arrow-drop-down]` would be

**Comment by naveenmadd** [comment]
const btn = await page.waitForFunction(() => {
    const btn = querySelectorShadowDom.querySelectorDeep("#menuButton > div > paper-input > iron-icon");
    return btn;
});
await btn.click();

**Comment by Georgegriff** [comment]
#13 might explain the issue @naveenmadd

**Comment by Georgegriff** [comment]
const btn = await page.waitForFunction(() => {


```
const btn = querySelectorShadowDom.querySelectorDeep("#menuButton > div > paper-input > iron-icon");
return btn;
}).asElement();
await btn.click();

```

Might work

**Comment by Georgegriff** [comment]
Issue resolved in https://github.com/Georgegriff/query-selector-shadow-dom/issues/13

Will update examples where required
