### ISSUE TITLE
Puppeteer examples not working

### ISSUE THREAD

**Issue by thernstig** [Georgegriff/query-selector-shadow-dom#13]
https://github.com/Georgegriff/query-selector-shadow-dom/blob/master/examples/puppeteer/clicking-elements.js

```javascript
const btn = await page.waitForFunction(() => {
    const btn = querySelectorShadowDom.querySelectorDeep(".btn-in-shadow-dom");
    return btn;
});
await btn.click();
```

This does not work due to that `page.waitForFunction` returns a JSHandle and not an ElementHandle. This it should be like this:

```javascript
const btn = (await page.waitForFunction(() => 
    querySelectorShadowDom.querySelectorDeep(".btn-in-shadow-dom")
)).asElement();
await btn.click();
```

**Comment by thernstig** [comment]
Same here: https://github.com/Georgegriff/query-selector-shadow-dom/blob/master/examples/puppeteer/typing-to-elements.js

**Comment by Georgegriff** [comment]
Interesting it was working did puppeteer change their API in 2.x?

**Comment by thernstig** [comment]
Yes, it seems they did.

**Comment by naveenmadd** [comment]
> https://github.com/Georgegriff/query-selector-shadow-dom/blob/master/examples/puppeteer/clicking-elements.js
> 
> ```js
> const btn = await page.waitForFunction(() => {
>     const btn = querySelectorShadowDom.querySelectorDeep(".btn-in-shadow-dom");
>     return btn;
> });
> await btn.click();
> ```
> 
> This does not work due to that `page.waitForFunction` returns a JSHandle and not an ElementHandle. This it should be like this:
> 
> ```js
> const btn = (await page.waitForFunction(() => 
>     querySelectorShadowDom.querySelectorDeep(".btn-in-shadow-dom");
> )).asElement();
> await btn.click();
> ```

even this has compiling issue, need to remove semi-colon in below line 
>     querySelectorShadowDom.querySelectorDeep(".btn-in-shadow-dom")
and even i'm getting same issue **Error: Node is either not visible or not an HTMLElement**
![image](https://user-images.githubusercontent.com/57717430/68954622-68050300-0792-11ea-869a-69ef27e0117c.png)

But surprisingly evaluateHandle with JSPath is working for my issue #12 
anyway Thanks for the response and support @Georgegriff @thernstig

**Comment by thernstig** [comment]
Updated original post to remove the extra ; that slipped in there.

**Comment by thernstig** [comment]
@Georgegriff I just also noticed that page.evaluateHandle also returns a JSHandle (and not ElementHandle) and page.evaluate only takes ElementHandle as function arguments: https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageevaluatepagefunction-args

So the examples needs more updates.

**Comment by Georgegriff** [comment]
@thernstig are you sure? I ran the examples last night against puppeteer 2 and they worked as expected

**Comment by thernstig** [comment]
@Georgegriff No you are correct, it seems it should work. I just read the docs from Puppeteer and thought it would not, due to this:

https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageevaluatepagefunction-args

> ElementHandle instances can be passed as arguments to the page.evaluate:

But reading the args it actually says:

> ...args <...Serializable|JSHandle> Arguments to pass to pageFunction

And since ElementHandle is a child of JSHandle, both works. Sorry for the noise.
