### ISSUE TITLE
Docs: querySelectorAllDeep, querySelectorDeep

### ISSUE THREAD

**Issue by thernstig** [Georgegriff/query-selector-shadow-dom#14]
The first part of the README.md explains that these two functions are exposed: querySelectorAllDeep, querySelectorDeep

It would be great to have a description of both, as I cannot figure out the difference easily.

**Comment by Georgegriff** [comment]
Documentation updated here https://github.com/Georgegriff/query-selector-shadow-dom/commit/47a4c0b33b199f070711ed9937ca224258a58e5c#diff-04c6e90faac2675aa89e2176d2eec7d8 @thernstig does this provide enough information?

**Comment by naveenmadd** [comment]
Seems Deep is working for elements inside shadow-root but not for nested shadow-roots
tried with AllDeep, this returns error as library is not defined(followed the same approach to import library as shown in examples, it's working for Deep but throwing error for AllDeep)
@Georgegriff (my code sample is in #12 )
JSpath is very static for nested shadow-roots, appreciated if I get some help with your library

**Comment by Georgegriff** [comment]
`querySelectorAllDeep` returns an array of matching elements, so if you're using it in the same way as the code sample it won't work, your code sample isn't using that method though, I don't really understand your issue

**Comment by thernstig** [comment]
@Georgegriff Looks great!
