### ISSUE TITLE
Playwright example not similar to Playwright "Custom Selector Engine" docs

### ISSUE THREAD

**Issue by thernstig** [Georgegriff/query-selector-shadow-dom#23]
References:
https://github.com/microsoft/playwright/blob/master/docs/api.md#selectorsregistername-script
https://github.com/microsoft/playwright/blob/master/docs/selectors.md#custom-selector-engines

Both show the API like `await selectors.register('tag', createTagNameEngine);` but the docs here show `await playwright.selectors.register(selectorEngine, { name: 'shadow' })`. The inconsistency is how the name and engine is set and in which order.

**Comment by thernstig** [comment]
Actually I see that what you have now is correct! See:
https://github.com/microsoft/playwright/blob/v0.11.1/docs/api.md#class-selectors

I assume the above code from master is how it soon will look. I assume it'd be good to keep this issue open to track that change?

**Comment by Georgegriff** [comment]
Sure keep it open :)

**Comment by Georgegriff** [comment]
Closing as playwright custom selector engine is not really needed anymore, since playwright added their own awesome shadow dom support
