### ISSUE TITLE
Need help with deepquery selector

### ISSUE THREAD

**Issue by alpriya87** [Georgegriff/query-selector-shadow-dom#25]
Here is the jspath :(Not able to click on the link )

document.querySelector("body > portal-web").shadowRoot.querySelector("#sink > details-web").shadowRoot.querySelector("div > history-page > div > ink-container > ink-card > div:nth-child(2) > div.historypage-items > mat-table > mat-row:nth-child(2) > mat-cell.ods-text__body--normal.component-width-insight.mat-cell.cdk-column-InSight.mat-column-InSight.ng-star-inserted > a")

I tried doing the below :
            const viewRelease = (await this.page.waitForFunction(() => {
                const viewRelease = querySelectorShadowDom.querySelectorDeep("div > history-page > div > ink-container > ink-card > div:nth-child(2) > div.historypage-items > mat-table > mat-row:nth-child(2) > mat-cell.ods-text__body--normal.component-width-insight.mat-cell.cdk-column-InSight.mat-column-InSight.ng-star-inserted > a")
                return viewRelease;
            })).asElement();
            await viewRelease.click();

OR  
const viewRelease = (await this.page.waitForFunction(() => {
                const viewRelease = querySelectorShadowDom.querySelectorDeep("div:nth-child(2) .ng-star-inserted > a")
                return viewRelease;
            })).asElement();
            await viewRelease.click();

Both did not work

**Comment by Georgegriff** [comment]
Hi i'm sorry to hear you're having issues, i will struggle to debug these scenarios to see if there are bugs in the library without reproduction code. I've not seen these issues raised before so it's possible that the css selector your using are not correct. I'm sorry i can't be of more help, all i can advise is to keep your selectors as simple as possible.
