### ISSUE TITLE
Should I add support for Protractor?

### ISSUE THREAD

**Issue by jan-molak** [Georgegriff/query-selector-shadow-dom#33]
Hi @Georgegriff and thanks for your amazing `query-selector-shadow-dom`!

I understand that your motivation behind writing this library was to provide support for Playwright, which now has its own CSS selector engine [inspired by your work](https://github.com/microsoft/playwright/issues/1375#issuecomment-614888459). In light of this, are you planning to continue to maintain this library?

If the answer is yes, would you be open to me submitting a PR adding support for Angular Protractor?

Thanks,
Jan

**Comment by Georgegriff** [comment]
This library existed before playwright, it's just playwright was the easiest to integrate with recently (until it wasn't needed anymore) But of course, more than happy! Although bare in mind have have zero experience with that test framework. So any examples/background or test cases would be great.

It may also be simpler to derive a new library with this is a dependency, up to you

**Comment by jan-molak** [comment]
Hi @Georgegriff! Many thanks for merging the PR 👍 
Is there anything left to do before we could have the new feature available on NPM?

**Comment by Georgegriff** [comment]
I'll try to release it today when I get chance

**Comment by Georgegriff** [comment]
Released in 0.6.0

**Comment by jan-molak** [comment]
Brilliant, thanks @Georgegriff :shipit:
