### ISSUE TITLE
'querySelectorDeep' is declared but its value is never read.ts(6133)

### ISSUE THREAD

**Issue by splmdevslack** [Georgegriff/query-selector-shadow-dom#42]
I am configuring the "query-selector-shadow-dom"  package in my protractor-TS code, 
and I have used querySelectorDeep in one of my function , Still I am getting error mentioned in subject.  can you have a look at it and let me know if its a configuration or a code issue

Posting Function below :

/**
    * Verify Specified id exist in specified view.
    * @returns {webdriver.promise.Promise<any>} a promise
    */
   public async verifyViewer(container, view): Promise<any> {
       
    var EC = protractor.ExpectedConditions;
    let getShadowElement: ElementFinder = $(view).element(by.querySelectorDeep('#'+container));

    browser.wait(EC.not(EC.visibilityOf(getShadowElement)));
    
}

**Comment by Georgegriff** [comment]
I'm afraid I don't know I don't use either typescript or protractor. @jan-molak contributed protractor support, hopefully they may be able to help

**Comment by jan-molak** [comment]
Hi @splmdevslack would you mind creating a repo on github with a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so that I could take a look?

**Comment by splmdevslack** [comment]
Hi @jan-molak , It was configuration issue from my end (in case of protractor , we don't have to use import , adding plugin in protractor config file resolved the issue ) .

Thanks for the quick response !! this issue can be closed.

still I will try to create repo with working example and post link here for reference
