### ISSUE TITLE
Code Cleanup Needed (inconsistent semicolon use)

### ISSUE THREAD

**Issue by minig0d** [Georgegriff/query-selector-shadow-dom#48]
Code currently gets mangled during compression due to inconsistent semicolon usage.  I am aware of ASI and typically code compresses fine with it, however something about the inconsistency seems to breaks the compression.

Suggest running through eslint with "rules": { "semi": ["error", "always"]} enabled to catch the 4 or 5 missing semicolons and ensure stability rather than relying on ASI https://eslint.org/docs/rules/semi)

**Comment by Georgegriff** [comment]
I'd happily accept a pr to fix this

**Comment by minig0d** [comment]
Can I just be lazy and tell you its lines: 31, 59, 88, 94, 95, 98, 99, 172? :)
It also flags "Expected a conditional expression and instead saw an assignment" (https://eslint.org/docs/rules/no-cond-assign) on line 165, which is valid but discouraged.
