### ISSUE TITLE
Code cleanup needed (missing semicolons)

### ISSUE THREAD

**Issue by minig0d** [Georgegriff/query-selector-shadow-dom#49]
Code currently gets mangled during compression due to inconsistent semicolon usage.  I am aware of ASI and typically code compresses fine with it, however something about the inconsistency seems to breaks the compression.

Suggest running through eslint with "rules": { "semi": ["error", "always"]} enabled to catch the 4 or 5 missing semicolons and ensure stability rather than relying on ASI https://eslint.org/docs/rules/semi)

**Comment by Georgegriff** [comment]
Closing as duplicate
