### ISSUE TITLE
Ability to override the document object

### ISSUE THREAD

**Issue by jasongardnerlv** [Georgegriff/query-selector-shadow-dom#5]
In [Testophobia](https://github.com/testophobia/testophobia), we need the ability to query for elements inside an iframe.  

We're not asking _q-s-s-d_ to do the actual queries across iframe boundaries,  but we would probably need to be able to pass into _querySelectorDeep_ some sort of optional __document__ argument, that would override its _document_ references, so we can tell it which document it should use for its queries (top-level vs. an iframe).

**Comment by Georgegriff** [comment]
Nice idea shouldn't be hard to add, will look into it

**Comment by Georgegriff** [comment]
@jasongardnerlv Just released a new version with this ehancement
